# Generated by Django 4.2.6 on 2025-12-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_merge_20250309_0000"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=255)),
                ("body_text", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="distributionlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="incident",
            name="default_extra_recipients",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="incidentmessage",
            name="recipients_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="incidentmessage",
            name="template_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="distributionlist",
            name="source",
            field=models.CharField(
                choices=[("custom", "Custom"), ("directory", "Active Directory")],
                db_index=True,
                default="directory",
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="DistributionListEntry",
        ),
        migrations.RemoveField(
            model_name="distributionlist",
            name="team",
        ),
    ]
