# Generated by Django 4.2.6 on 2025-12-20 16:59

from django.db import migrations

from communications.constants import DEFAULT_EMAIL_TEMPLATES


def seed_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("communications", "EmailTemplate")
    for template in DEFAULT_EMAIL_TEMPLATES:
        EmailTemplate.objects.update_or_create(
            key=template["id"],
            defaults={
                "name": template.get("label") or template["id"],
                "description": template.get("description", ""),
                "subject": template.get("subject", ""),
                "body_text": template.get("body", ""),
                "body_html": template.get("html_body", ""),
                "version": template.get("version", 1),
                "is_active": True,
            },
        )


def noop(apps, schema_editor):
    # Templates can be edited via the admin, so we do not delete them on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "communications",
            "0004_emailtemplate_alter_distributionlist_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(seed_templates, reverse_code=noop),
    ]
