# Generated by Django 4.2.6 on 2025-12-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="affected_regions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="incident",
            name="distribution_lists",
            field=models.ManyToManyField(
                blank=True,
                related_name="incidents",
                to="communications.distributionlist",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="inc_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("major", "Major"),
                    ("critical", "Critical"),
                    ("informational", "Informational"),
                ],
                default="major",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="next_communication_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="problem_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="workaround",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentmessage",
            name="distribution_lists",
            field=models.ManyToManyField(
                blank=True,
                related_name="incident_messages_multi",
                to="communications.distributionlist",
            ),
        ),
        migrations.AddField(
            model_name="incidentmessage",
            name="next_communication_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentmessage",
            name="point_of_contact",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="incidentmessage",
            name="problem_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentmessage",
            name="workaround",
            field=models.TextField(blank=True),
        ),
    ]
