# Backend
HOST_URL=https://54.81.160.198
BACKEND_PORT=8000
DJANGO_SECRET_KEY=prod-secret-key
DEBUG=False
ALLOWED_HOSTS=54.81.160.198,localhost,127.0.0.1

# Azure SSO
AZURE_TENANT_ID=05ceb559-e89f-4e43-a141-34567baa8838
AZURE_CLIENT_ID=2674c689-eca2-4af7-8a21-02a6fccbc04d
AZURE_CLIENT_SECRET=KER8Q~wLpPH~LyHaCKQNuY7cPQ46xSMbVAQ~UdoU

# Redirect URIs (Nginx handles HTTPS)
AZURE_REDIRECT_URI=${HOST_URL}/oauth2/callback/
POST_LOGOUT_REDIRECT_URI=${HOST_URL}/

# CORS / CSRF
CORS_ALLOWED_ORIGINS=${HOST_URL}
CSRF_TRUSTED_ORIGINS=${HOST_URL}
CORS_ALLOW_CREDENTIALS=True

# Email (production - update with real SMTP credentials)
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=girish.lc.photos2@gmail.com
EMAIL_HOST_PASSWORD=jhazpenfiuhduvvx
DEFAULT_FROM_EMAIL=girish.lc.photos2@gmail.com

# SDT ingestion
MAILBOX_ADDRESS=maintenance@example.com
EMAIL_INGEST_MODE=poll
POLL_INTERVAL_SECONDS=300
ALLOWED_SENDER_DOMAINS=vendor.example.com,alerts.example.com
LOGICMONITOR_ACCOUNT=your-account
LOGICMONITOR_ACCESS_ID=your-access-id
LOGICMONITOR_ACCESS_KEY=your-access-key
LOGICMONITOR_API_BASE=
