# Generated by Django 4.2.6 on 2025-12-04 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_profiles(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)
    UserProfile = apps.get_model("USER", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user_id=user.id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("USER", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("team_admin", "Team Admin"),
                            ("system_admin", "System Admin"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_manually",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the current role was explicitly assigned by an admin.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
            },
        ),
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
