# Generated by Django 4.2.6 on 2026-02-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdt_automation", "0004_allow_sdtrequest_email_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteCodeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_site_code",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                ("lm_site_code", models.CharField(db_index=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["vendor_site_code"],
            },
        ),
        migrations.CreateModel(
            name="SDTQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_id", models.CharField(max_length=255, unique=True)),
                ("vendor_site_code", models.CharField(db_index=True, max_length=120)),
                (
                    "lm_site_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, null=True
                    ),
                ),
                ("start_time_utc", models.DateTimeField(db_index=True)),
                ("end_time_utc", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "circuit_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("single", "Single"),
                            ("dual", "Dual"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("site", "Site"), ("device", "Device")],
                        default="site",
                        max_length=20,
                    ),
                ),
                ("target_ids", models.JSONField(blank=True, default=list)),
                ("lm_sdt_ids", models.JSONField(blank=True, default=list)),
                ("verification_status", models.CharField(blank=True, max_length=40)),
                ("verification_details", models.JSONField(blank=True, default=dict)),
                ("parsed_payload", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_time_utc", "-created_at"],
                "indexes": [
                    models.Index(fields=["maintenance_id"], name="sdtq_maint_idx"),
                    models.Index(fields=["status"], name="sdtq_status_idx"),
                    models.Index(fields=["start_time_utc"], name="sdtq_start_idx"),
                    models.Index(fields=["end_time_utc"], name="sdtq_end_idx"),
                    models.Index(fields=["vendor_site_code"], name="sdtq_vendor_idx"),
                    models.Index(fields=["lm_site_code"], name="sdtq_lm_idx"),
                ],
            },
        ),
    ]
